import type { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1769402436295 implements MigrationInterface {
    name = 'Initial1769402436295'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "address" text, "phone_number" character varying(20), "email" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "is_main" boolean NOT NULL DEFAULT false, "accent_color" character varying(20) NOT NULL DEFAULT 'red', "txt_on_accent_color" character varying(20) NOT NULL DEFAULT 'white', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c2c16397fa98d34f8db37684c41" UNIQUE ("slug"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c2c16397fa98d34f8db37684c4" ON "branches" ("slug") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "image" character varying, "is_active" boolean NOT NULL DEFAULT true, "branch_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "sku" character varying, "images" jsonb, "category_id" uuid, "brand_id" uuid, "branch_id" uuid NOT NULL, "price" numeric NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_featured" boolean NOT NULL DEFAULT false, "quantity" integer NOT NULL DEFAULT '0', "low_stock_threshold" integer NOT NULL DEFAULT '10', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4c9fb58de893725258746385e16" UNIQUE ("name"), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5f641129265a386fc2908ce554" ON "products" ("name", "sku") `);
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "logo_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "branch_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6" UNIQUE ("name"), CONSTRAINT "UQ_b15428f362be2200922952dc268" UNIQUE ("slug"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "permissions" character varying array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d6589353e41edae39bce77e8a40" UNIQUE ("slug"), CONSTRAINT "PK_87101d9c9d1604a36152cfad1c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d6589353e41edae39bce77e8a4" ON "staff_roles" ("slug") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "performed_by_id" uuid, "target_id" character varying, "target_type" character varying(100), "action" character varying(100) NOT NULL, "description" text NOT NULL, "metadata" jsonb, "ip_address" character varying(45), "user_agent" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bd66339fb98914129e1780301" ON "audit_logs" ("performed_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a358c00ae08bdea24880372d7a" ON "audit_logs" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE TABLE "staff" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_account_id" uuid NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "primary_phone_number" character varying(20), "secondary_phone_number" character varying(20), "photo_url" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a1272aa38a3cdcf5cfe518ffaf1" UNIQUE ("user_account_id"), CONSTRAINT "REL_a1272aa38a3cdcf5cfe518ffaf" UNIQUE ("user_account_id"), CONSTRAINT "PK_e4ee98bb552756c180aec1e854a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "refresh_token" character varying NOT NULL, "ip_address" character varying(45), "user_agent" character varying(500), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c862499023be8feec98129d4e96" UNIQUE ("refresh_token"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_085d540d9f418cfbdc7bd55bb1" ON "sessions" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c862499023be8feec98129d4e9" ON "sessions" ("refresh_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_9cfe37d28c3b229a350e086d94" ON "sessions" ("expires_at") `);
        await queryRunner.query(`CREATE TYPE "public"."otps_type_enum" AS ENUM('login', 'password_reset', 'email_verification')`);
        await queryRunner.query(`CREATE TABLE "otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "verification_token" uuid NOT NULL, "token" character varying(6) NOT NULL, "type" "public"."otps_type_enum" NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "ip_address" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd65700a251465579f9a84d76c" ON "otps" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ce162936e9fe56b1fb44a4880" ON "otps" ("verification_token") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cdbfb39b42fa6ef1469175acf" ON "otps" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_3938bb24b38ad395af30230bde" ON "otps" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "brand_id" uuid, "name" character varying(200) NOT NULL, "color" character varying(50), "number_plate" character varying(20), "vin_number" character varying(50), "year" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_account_id" uuid, "name" character varying(200) NOT NULL, "phone_number" character varying(20) NOT NULL, "email" character varying(255), "address" text, "notes" text, "photo_url" character varying(500), "branch_id" uuid, "shipping_address" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_ffdac370559932474b0709417b" UNIQUE ("user_account_id"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "hashed_password" character varying NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "account_type" character varying(50) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_payments_method_enum" AS ENUM('cash', 'bank_transfer', 'mobile_money', 'pos', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."sale_payments_status_enum" AS ENUM('pending', 'confirmed', 'denied')`);
        await queryRunner.query(`CREATE TABLE "sale_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_id" uuid NOT NULL, "amount" numeric NOT NULL, "method" "public"."sale_payments_method_enum" NOT NULL, "reference" character varying, "status" "public"."sale_payments_status_enum" NOT NULL DEFAULT 'pending', "recorded_by_id" uuid NOT NULL, "approved_by_id" uuid, "approved_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1117d02608a00d131b95f60a58e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('processing', 'delivered', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_id" character varying(50) NOT NULL, "customer_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "created_by_id" uuid, "status" "public"."sales_status_enum" NOT NULL DEFAULT 'processing', "subtotal" numeric NOT NULL DEFAULT '0', "tax_amount" numeric NOT NULL DEFAULT '0', "total_amount" numeric NOT NULL DEFAULT '0', "amount_paid" numeric NOT NULL DEFAULT '0', "balance" numeric NOT NULL DEFAULT '0', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7e3ae967699d6493819bf01d822" UNIQUE ("sale_id"), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7e3ae967699d6493819bf01d82" ON "sales" ("sale_id") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "product_name" character varying(255) NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_payments_method_enum" AS ENUM('bank_transfer', 'mobile_money', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."order_payments_status_enum" AS ENUM('pending', 'confirmed', 'denied')`);
        await queryRunner.query(`CREATE TABLE "order_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "amount" numeric NOT NULL, "method" "public"."order_payments_method_enum" NOT NULL, "reference" character varying, "status" "public"."order_payments_status_enum" NOT NULL DEFAULT 'pending', "confirmed_by_id" uuid, "confirmed_at" TIMESTAMP, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc14b014a69d39c7bbc4a154b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" character varying(50) NOT NULL, "customer_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "total_amount" numeric NOT NULL DEFAULT '0', "amount_paid" numeric NOT NULL DEFAULT '0', "shipping_address" text NOT NULL, "notes" text, "cancellation_reason" text, "cancelled_at" TIMESTAMP, "cancelled_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cad55b3cb25b38be94d2ce831db" UNIQUE ("order_id"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cad55b3cb25b38be94d2ce831d" ON "orders" ("order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."contact_messages_status_enum" AS ENUM('unread', 'read', 'replied')`);
        await queryRunner.query(`CREATE TABLE "contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "phone" character varying(20), "subject" character varying(255) NOT NULL, "message" text NOT NULL, "status" "public"."contact_messages_status_enum" NOT NULL DEFAULT 'unread', "branch_id" uuid NOT NULL, "reply_content" text, "replied_at" TIMESTAMP WITH TIME ZONE, "replied_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b74f96eb2edd977ccfba6533293" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11eb2c3d2d9e07f264907f40ef" ON "contact_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e66bf825d2c4bbf3c3cb7946ec" ON "contact_messages" ("branch_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('rent', 'transport', 'salary', 'allowance', 'utilities', 'supplies', 'maintenance', 'marketing', 'insurance', 'taxes', 'equipment', 'communication', 'travel', 'training', 'miscellaneous')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expense_id" character varying(50) NOT NULL, "branch_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "amount" numeric(12,2) NOT NULL, "category" "public"."expenses_category_enum" NOT NULL, "expense_date" date NOT NULL, "receipt_url" character varying(500), "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'pending', "created_by_id" uuid NOT NULL, "reviewed_by_id" uuid, "reviewed_at" TIMESTAMP, "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e05b03cdc63e9849adcebeb0118" UNIQUE ("expense_id"), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_628127744cec871381f6ed5066" ON "expenses" ("branch_id", "expense_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f21bf65a5ab556d1920941908" ON "expenses" ("branch_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e05b03cdc63e9849adcebeb011" ON "expenses" ("expense_id") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "email" character varying(255), "phone" character varying(50), "address" text, "contact_person" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "branch_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6f01a03dcb1aa33822e19534cd6" UNIQUE ("code"), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6f01a03dcb1aa33822e19534cd" ON "suppliers" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'partially_received', 'received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "po_number" character varying(50) NOT NULL, "supplier_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "expected_delivery_date" date, "total_amount" numeric NOT NULL DEFAULT '0', "notes" text, "created_by_id" uuid NOT NULL, "approved_by_id" uuid, "approved_at" TIMESTAMP, "rejection_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_74065a5d2b8c4c14b8b8fcf0159" UNIQUE ("po_number"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_74065a5d2b8c4c14b8b8fcf015" ON "purchase_orders" ("po_number") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "product_name" character varying(255) NOT NULL, "product_sku" character varying(100), "quantity" integer NOT NULL, "unit_cost" numeric NOT NULL, "received_quantity" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_roles_map" ("staff_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_353654cae5872c00af16d40af0e" PRIMARY KEY ("staff_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_76b3e79ac07edb00cb8d1d9b58" ON "staff_roles_map" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_be971ab25bc710823de67c3db5" ON "staff_roles_map" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "staff_branches_map" ("staff_id" uuid NOT NULL, "branch_id" uuid NOT NULL, CONSTRAINT "PK_1cc5c96e368b298a66648e56dd1" PRIMARY KEY ("staff_id", "branch_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d5597ca51dc4084aa11d73b18" ON "staff_branches_map" ("staff_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6df4f06eb239e29d7569d7d6df" ON "staff_branches_map" ("branch_id") `);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_0011937b9b4cd88d39accdd6edf" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de720484cb95d8752861e507921" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "FK_9f436cf2256720659312168710d" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_8bd66339fb98914129e1780301c" FOREIGN KEY ("performed_by_id") REFERENCES "staff"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff" ADD CONSTRAINT "FK_a1272aa38a3cdcf5cfe518ffaf1" FOREIGN KEY ("user_account_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otps" ADD CONSTRAINT "FK_3938bb24b38ad395af30230bded" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_73799befe8cf03cf49595d96d6d" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_2ae4f4add790956c0f16a48cb74" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_ffdac370559932474b0709417bc" FOREIGN KEY ("user_account_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_a307ea7ea650f6a98dcf33f717f" FOREIGN KEY ("recorded_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_payments" ADD CONSTRAINT "FK_845d9dd29e92bfa47dfeb10b0dd" FOREIGN KEY ("approved_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_236f3154522de80a98f87c66b84" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_2ba538723e1224ec7140384033e" FOREIGN KEY ("created_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_payments" ADD CONSTRAINT "FK_5d2ebca202f9d9370a001a571ba" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_payments" ADD CONSTRAINT "FK_85440012bfeb625094424500b2e" FOREIGN KEY ("confirmed_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_17b723da2c12837f4bc21e33398" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_2cc05592859eba0cf60c44b80d3" FOREIGN KEY ("cancelled_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_messages" ADD CONSTRAINT "FK_5c170fff88bfc0a0c4268169258" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_messages" ADD CONSTRAINT "FK_18f0ce203d636d1b8822197b774" FOREIGN KEY ("replied_by") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_866a3b82ff438efc19c2398cda6" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_cb8a9ecdb628ea1befdbaf6e078" FOREIGN KEY ("created_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_01b9b60912e2cc1ebfc6e5b6441" FOREIGN KEY ("reviewed_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_ce35fd787e09aecdb311aaff66c" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_1fdd0d65d22a9a9b3d43d7392d1" FOREIGN KEY ("created_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_fc976210717def7ce55b4313629" FOREIGN KEY ("approved_by_id") REFERENCES "staff"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_d5089517fc19b1b9fb04454740c" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_roles_map" ADD CONSTRAINT "FK_76b3e79ac07edb00cb8d1d9b587" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff_roles_map" ADD CONSTRAINT "FK_be971ab25bc710823de67c3db54" FOREIGN KEY ("role_id") REFERENCES "staff_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_branches_map" ADD CONSTRAINT "FK_2d5597ca51dc4084aa11d73b185" FOREIGN KEY ("staff_id") REFERENCES "staff"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "staff_branches_map" ADD CONSTRAINT "FK_6df4f06eb239e29d7569d7d6df1" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "staff_branches_map" DROP CONSTRAINT "FK_6df4f06eb239e29d7569d7d6df1"`);
        await queryRunner.query(`ALTER TABLE "staff_branches_map" DROP CONSTRAINT "FK_2d5597ca51dc4084aa11d73b185"`);
        await queryRunner.query(`ALTER TABLE "staff_roles_map" DROP CONSTRAINT "FK_be971ab25bc710823de67c3db54"`);
        await queryRunner.query(`ALTER TABLE "staff_roles_map" DROP CONSTRAINT "FK_76b3e79ac07edb00cb8d1d9b587"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_d5089517fc19b1b9fb04454740c"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_fc976210717def7ce55b4313629"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_1fdd0d65d22a9a9b3d43d7392d1"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_2b0e6536d50d20e0d46f9e386c3"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_ce35fd787e09aecdb311aaff66c"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_01b9b60912e2cc1ebfc6e5b6441"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_cb8a9ecdb628ea1befdbaf6e078"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_866a3b82ff438efc19c2398cda6"`);
        await queryRunner.query(`ALTER TABLE "contact_messages" DROP CONSTRAINT "FK_18f0ce203d636d1b8822197b774"`);
        await queryRunner.query(`ALTER TABLE "contact_messages" DROP CONSTRAINT "FK_5c170fff88bfc0a0c4268169258"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_2cc05592859eba0cf60c44b80d3"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_17b723da2c12837f4bc21e33398"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "order_payments" DROP CONSTRAINT "FK_85440012bfeb625094424500b2e"`);
        await queryRunner.query(`ALTER TABLE "order_payments" DROP CONSTRAINT "FK_5d2ebca202f9d9370a001a571ba"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_2ba538723e1224ec7140384033e"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_236f3154522de80a98f87c66b84"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_845d9dd29e92bfa47dfeb10b0dd"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_a307ea7ea650f6a98dcf33f717f"`);
        await queryRunner.query(`ALTER TABLE "sale_payments" DROP CONSTRAINT "FK_0e4445597642c2456ebdd7e23b1"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_ffdac370559932474b0709417bc"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_2ae4f4add790956c0f16a48cb74"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_73799befe8cf03cf49595d96d6d"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627"`);
        await queryRunner.query(`ALTER TABLE "otps" DROP CONSTRAINT "FK_3938bb24b38ad395af30230bded"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "staff" DROP CONSTRAINT "FK_a1272aa38a3cdcf5cfe518ffaf1"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_8bd66339fb98914129e1780301c"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "FK_9f436cf2256720659312168710d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de720484cb95d8752861e507921"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_1530a6f15d3c79d1b70be98f2be"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_0011937b9b4cd88d39accdd6edf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6df4f06eb239e29d7569d7d6df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d5597ca51dc4084aa11d73b18"`);
        await queryRunner.query(`DROP TABLE "staff_branches_map"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be971ab25bc710823de67c3db5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76b3e79ac07edb00cb8d1d9b58"`);
        await queryRunner.query(`DROP TABLE "staff_roles_map"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74065a5d2b8c4c14b8b8fcf015"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f01a03dcb1aa33822e19534cd"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e05b03cdc63e9849adcebeb011"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f21bf65a5ab556d1920941908"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_628127744cec871381f6ed5066"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e66bf825d2c4bbf3c3cb7946ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11eb2c3d2d9e07f264907f40ef"`);
        await queryRunner.query(`DROP TABLE "contact_messages"`);
        await queryRunner.query(`DROP TYPE "public"."contact_messages_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cad55b3cb25b38be94d2ce831d"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_payments"`);
        await queryRunner.query(`DROP TYPE "public"."order_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e3ae967699d6493819bf01d82"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`DROP TABLE "sale_payments"`);
        await queryRunner.query(`DROP TYPE "public"."sale_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sale_payments_method_enum"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3938bb24b38ad395af30230bde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cdbfb39b42fa6ef1469175acf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ce162936e9fe56b1fb44a4880"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd65700a251465579f9a84d76c"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP TYPE "public"."otps_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9cfe37d28c3b229a350e086d94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c862499023be8feec98129d4e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_085d540d9f418cfbdc7bd55bb1"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a358c00ae08bdea24880372d7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bd66339fb98914129e1780301"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6589353e41edae39bce77e8a4"`);
        await queryRunner.query(`DROP TABLE "staff_roles"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f641129265a386fc2908ce554"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2c16397fa98d34f8db37684c4"`);
        await queryRunner.query(`DROP TABLE "branches"`);
    }

}
