import { Injectable } from '@nestjs/common';
import { SalesReportData } from './sales-report.service';
import { ExpenseReportData } from './expense-report.service';
import { InventoryReportData } from './inventory-report.service';
import { ProcurementReportData } from './procurement-report.service';
import { FinancialReportData } from './financial-report.service';

// eslint-disable-next-line @typescript-eslint/no-require-imports
const PDFDocument = require('pdfkit');

@Injectable()
export class ReportPdfService {
  private readonly themeColor = '#dc2626';
  private readonly textPrimary = '#172554';
  private readonly textSecondary = '#64748b';
  private readonly bgLight = '#f8fafc';

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat('en-UG', {
      style: 'currency',
      currency: 'UGX',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  }

  /**
   * Truncate text to a maximum length with ellipsis
   */
  private truncateText(text: string, maxLength: number): string {
    if (!text || text.length <= maxLength) {
      return text;
    }
    return text.substring(0, maxLength - 3) + '...';
  }

  private formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString('en-UG', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }

  private drawHeader(
    doc: PDFKit.PDFDocument,
    title: string,
    branchName: string,
    dateRange: { startDate: string; endDate: string },
    pageWidth: number
  ): void {
    // Company name
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .fillColor(this.themeColor)
      .text('SMOKE POS', 50, 45);

    // Report title
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor(this.themeColor)
      .text(title.toUpperCase(), 300, 45, { align: 'right' });

    doc.moveDown(1.5);

    // Info box
    const boxY = doc.y;
    doc.rect(50, boxY, pageWidth, 40).fill(this.bgLight);

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('BRANCH', 65, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(branchName, 65, boxY + 20);

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('PERIOD', 250, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(
        `${this.formatDate(dateRange.startDate)} - ${this.formatDate(dateRange.endDate)}`,
        250,
        boxY + 20
      );

    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text('GENERATED', 450, boxY + 8);
    doc
      .fillColor(this.textPrimary)
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(new Date().toLocaleDateString('en-UG'), 450, boxY + 20);

    doc.y = boxY + 55;
  }

  private drawSummaryCard(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    width: number,
    label: string,
    value: string
  ): void {
    doc.rect(x, y, width, 50).fill(this.bgLight);
    doc
      .fillColor(this.textSecondary)
      .fontSize(9)
      .font('Helvetica')
      .text(label, x + 10, y + 10, { width: width - 20 });
    doc
      .fillColor(this.textPrimary)
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(value, x + 10, y + 26, { width: width - 20 });
  }

  private drawSectionTitle(doc: PDFKit.PDFDocument, title: string): void {
    doc.moveDown(1);
    doc.fillColor(this.themeColor).fontSize(12).font('Helvetica-Bold').text(title);
    doc.moveDown(0.5);
  }

  private drawTableHeader(
    doc: PDFKit.PDFDocument,
    columns: { label: string; x: number; width: number }[]
  ): number {
    const y = doc.y;
    doc.rect(50, y, doc.page.width - 100, 25).fill(this.themeColor);
    doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');

    for (const col of columns) {
      doc.text(col.label, col.x, y + 8, { width: col.width });
    }

    return y + 25;
  }

  private drawFooter(doc: PDFKit.PDFDocument, pageWidth: number): void {
    const footerY = doc.page.height - 50;
    doc
      .fillColor(this.textSecondary)
      .fontSize(8)
      .font('Helvetica')
      .text('Generated by SMOKE POS Management System', 50, footerY, {
        width: pageWidth,
        align: 'center',
      });
  }

  // Sales Report PDF
  async generateSalesReportPdf(data: SalesReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Sales Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 20) / 4;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL REVENUE',
        this.formatCurrency(data.summary.totalRevenue)
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'TOTAL TAX',
        this.formatCurrency(data.summary.totalTax)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'TOTAL SALES',
        data.summary.totalSales.toString()
      );
      this.drawSummaryCard(
        doc,
        65 + cardWidth * 3,
        cardY,
        cardWidth,
        'AVG ORDER',
        this.formatCurrency(data.summary.averageOrderValue)
      );

      doc.y = cardY + 65;

      // Top Products
      this.drawSectionTitle(doc, 'Top Selling Products');
      const columns = [
        { label: 'Product', x: 55, width: 200 },
        { label: 'Qty Sold', x: 260, width: 80 },
        { label: 'Revenue', x: 350, width: 100 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < Math.min(data.topProducts.length, 10); i++) {
        const product = data.topProducts[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
        }
        doc.fillColor(this.textPrimary);
        doc.text(this.truncateText(product.productName, 40), 55, tableY + 6, { width: 200 });
        doc.text(product.quantitySold.toString(), 260, tableY + 6, { width: 80 });
        doc.text(this.formatCurrency(product.revenue), 350, tableY + 6, { width: 100 });
        tableY += 20;
      }

      // Sales by Status
      if (data.salesByStatus.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Sales by Status');
        const statusColumns = [
          { label: 'Status', x: 55, width: 150 },
          { label: 'Count', x: 210, width: 80 },
          { label: 'Revenue', x: 300, width: 100 },
        ];
        tableY = this.drawTableHeader(doc, statusColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.salesByStatus.length; i++) {
          const status = data.salesByStatus[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(status.status.charAt(0).toUpperCase() + status.status.slice(1), 55, tableY + 6, {
            width: 150,
          });
          doc.text(status.count.toString(), 210, tableY + 6, { width: 80 });
          doc.text(this.formatCurrency(status.revenue), 300, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Expense Report PDF
  async generateExpenseReportPdf(data: ExpenseReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Expense Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 15) / 3;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'APPROVED EXPENSES',
        this.formatCurrency(data.summary.approvedExpenses)
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'PENDING',
        this.formatCurrency(data.summary.pendingExpenses)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'TOTAL COUNT',
        data.summary.expenseCount.toString()
      );

      doc.y = cardY + 65;

      // Expenses by Category
      this.drawSectionTitle(doc, 'Expenses by Category');
      const columns = [
        { label: 'Category', x: 55, width: 150 },
        { label: 'Amount', x: 210, width: 100 },
        { label: 'Count', x: 320, width: 60 },
        { label: 'Percentage', x: 390, width: 80 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < data.byCategory.length; i++) {
        const cat = data.byCategory[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
        }
        doc.fillColor(this.textPrimary);
        doc.text(
          cat.category.charAt(0).toUpperCase() + cat.category.slice(1).replace('_', ' '),
          55,
          tableY + 6,
          { width: 150 }
        );
        doc.text(this.formatCurrency(cat.amount), 210, tableY + 6, { width: 100 });
        doc.text(cat.count.toString(), 320, tableY + 6, { width: 60 });
        doc.text(`${cat.percentage.toFixed(1)}%`, 390, tableY + 6, { width: 80 });
        tableY += 20;
      }

      // Top Expenses
      if (data.topExpenses.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Top Expenses');
        const expColumns = [
          { label: 'Title', x: 55, width: 180 },
          { label: 'Category', x: 240, width: 100 },
          { label: 'Amount', x: 350, width: 100 },
        ];
        tableY = this.drawTableHeader(doc, expColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.topExpenses.length, 8); i++) {
          const exp = data.topExpenses[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(exp.title, 35), 55, tableY + 6, { width: 180 });
          doc.text(exp.category.charAt(0).toUpperCase() + exp.category.slice(1), 240, tableY + 6, {
            width: 100,
          });
          doc.text(this.formatCurrency(exp.amount), 350, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Inventory Report PDF
  async generateInventoryReportPdf(data: InventoryReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      // Simple header for inventory (no date range)
      doc
        .fontSize(18)
        .font('Helvetica-Bold')
        .fillColor(this.themeColor)
        .text('SMOKE POS', 50, 45);

      doc
        .fontSize(24)
        .font('Helvetica-Bold')
        .fillColor(this.themeColor)
        .text('INVENTORY REPORT', 300, 45, { align: 'right' });

      doc.moveDown(1.5);

      const boxY = doc.y;
      doc.rect(50, boxY, pageWidth, 40).fill(this.bgLight);

      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('BRANCH', 65, boxY + 8);
      doc
        .fillColor(this.textPrimary)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(data.branch.name, 65, boxY + 20);

      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('GENERATED', 450, boxY + 8);
      doc
        .fillColor(this.textPrimary)
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(new Date().toLocaleDateString('en-UG'), 450, boxY + 20);

      doc.y = boxY + 55;

      // Summary cards
      const cardWidth = (pageWidth - 20) / 4;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL PRODUCTS',
        data.summary.totalProducts.toString()
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'STOCK VALUE',
        this.formatCurrency(data.summary.totalStockValue)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'LOW STOCK',
        data.summary.lowStockCount.toString()
      );
      this.drawSummaryCard(
        doc,
        65 + cardWidth * 3,
        cardY,
        cardWidth,
        'OUT OF STOCK',
        data.summary.outOfStockCount.toString()
      );

      doc.y = cardY + 65;

      // Low Stock Products
      if (data.lowStockProducts.length > 0) {
        this.drawSectionTitle(doc, 'Low Stock Alert');
        const columns = [
          { label: 'Product', x: 55, width: 180 },
          { label: 'Qty', x: 240, width: 50 },
          { label: 'Threshold', x: 295, width: 60 },
          { label: 'Price', x: 360, width: 80 },
        ];
        let tableY = this.drawTableHeader(doc, columns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.lowStockProducts.length, 15); i++) {
          const product = data.lowStockProducts[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#fef2f2');
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(product.name, 35), 55, tableY + 6, { width: 180 });
          doc
            .fillColor('#dc2626')
            .text(product.quantity.toString(), 240, tableY + 6, { width: 50 });
          doc
            .fillColor(this.textPrimary)
            .text(product.lowStockThreshold.toString(), 295, tableY + 6, { width: 60 });
          doc.text(this.formatCurrency(product.price), 360, tableY + 6, { width: 80 });
          tableY += 20;
        }
      }

      // Stock by Category
      if (data.stockByCategory.length > 0) {
        doc.addPage();
        this.drawSectionTitle(doc, 'Stock by Category');
        const catColumns = [
          { label: 'Category', x: 55, width: 150 },
          { label: 'Products', x: 210, width: 70 },
          { label: 'Quantity', x: 285, width: 70 },
          { label: 'Value', x: 360, width: 100 },
        ];
        let tableY = this.drawTableHeader(doc, catColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.stockByCategory.length; i++) {
          const cat = data.stockByCategory[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(cat.categoryName, 55, tableY + 6, { width: 150 });
          doc.text(cat.productCount.toString(), 210, tableY + 6, { width: 70 });
          doc.text(cat.totalQuantity.toString(), 285, tableY + 6, { width: 70 });
          doc.text(this.formatCurrency(cat.totalValue), 360, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Procurement Report PDF
  async generateProcurementReportPdf(data: ProcurementReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Procurement Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards
      const cardWidth = (pageWidth - 15) / 3;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL POs',
        data.summary.totalPurchaseOrders.toString()
      );
      this.drawSummaryCard(
        doc,
        55 + cardWidth,
        cardY,
        cardWidth,
        'TOTAL VALUE',
        this.formatCurrency(data.summary.totalAmount)
      );
      this.drawSummaryCard(
        doc,
        60 + cardWidth * 2,
        cardY,
        cardWidth,
        'RECEIVED VALUE',
        this.formatCurrency(data.summary.receivedAmount)
      );

      doc.y = cardY + 65;

      // PO by Status
      this.drawSectionTitle(doc, 'Purchase Orders by Status');
      const columns = [
        { label: 'Status', x: 55, width: 150 },
        { label: 'Count', x: 210, width: 70 },
        { label: 'Amount', x: 285, width: 100 },
        { label: '%', x: 390, width: 60 },
      ];
      let tableY = this.drawTableHeader(doc, columns);

      doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
      for (let i = 0; i < data.byStatus.length; i++) {
        const status = data.byStatus[i];
        if (i % 2 === 0) {
          doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
        }
        doc.fillColor(this.textPrimary);
        doc.text(
          status.status.replace('_', ' ').charAt(0).toUpperCase() +
            status.status.replace('_', ' ').slice(1),
          55,
          tableY + 6,
          { width: 150 }
        );
        doc.text(status.count.toString(), 210, tableY + 6, { width: 70 });
        doc.text(this.formatCurrency(status.amount), 285, tableY + 6, { width: 100 });
        doc.text(`${status.percentage.toFixed(1)}%`, 390, tableY + 6, { width: 60 });
        tableY += 20;
      }

      // By Supplier
      if (data.bySupplier.length > 0) {
        doc.y = tableY + 10;
        this.drawSectionTitle(doc, 'Orders by Supplier');
        const supColumns = [
          { label: 'Supplier', x: 55, width: 180 },
          { label: 'Orders', x: 240, width: 70 },
          { label: 'Total Amount', x: 320, width: 120 },
        ];
        tableY = this.drawTableHeader(doc, supColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.bySupplier.length, 10); i++) {
          const sup = data.bySupplier[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(this.truncateText(sup.supplierName, 35), 55, tableY + 6, { width: 180 });
          doc.text(sup.orderCount.toString(), 240, tableY + 6, { width: 70 });
          doc.text(this.formatCurrency(sup.totalAmount), 320, tableY + 6, { width: 120 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }

  // Financial Report PDF
  async generateFinancialReportPdf(data: FinancialReportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;

      this.drawHeader(doc, 'Financial Report', data.branch.name, data.dateRange, pageWidth);

      // Summary cards - Row 1: Revenue, Expenses, COGS, Tax
      const cardWidth = (pageWidth - 20) / 4;
      const cardGap = 5;
      const cardY = doc.y;
      this.drawSummaryCard(
        doc,
        50,
        cardY,
        cardWidth,
        'TOTAL REVENUE',
        this.formatCurrency(data.summary.totalRevenue)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap),
        cardY,
        cardWidth,
        'TOTAL EXPENSES',
        this.formatCurrency(data.summary.totalExpenses)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 2,
        cardY,
        cardWidth,
        'COST OF GOODS SOLD',
        this.formatCurrency(data.summary.costOfGoodsSold)
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 3,
        cardY,
        cardWidth,
        'TOTAL TAX',
        this.formatCurrency(data.summary.totalTax)
      );

      // Row 2: Gross Profit, Net Profit, Gross Margin, Net Margin
      const row2Y = cardY + 60;

      // Gross profit card with color
      const grossProfitX = 50;
      doc
        .rect(grossProfitX, row2Y, cardWidth, 50)
        .fill(data.summary.grossProfit >= 0 ? '#dcfce7' : '#fef2f2');
      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('GROSS PROFIT', grossProfitX + 10, row2Y + 10, { width: cardWidth - 20 });
      doc
        .fillColor(data.summary.grossProfit >= 0 ? '#16a34a' : '#dc2626')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(this.formatCurrency(data.summary.grossProfit), grossProfitX + 10, row2Y + 26, {
          width: cardWidth - 20,
        });

      // Net profit card with color
      const netProfitX = 50 + (cardWidth + cardGap);
      doc
        .rect(netProfitX, row2Y, cardWidth, 50)
        .fill(data.summary.netProfit >= 0 ? '#dcfce7' : '#fef2f2');
      doc
        .fillColor(this.textSecondary)
        .fontSize(9)
        .font('Helvetica')
        .text('NET PROFIT', netProfitX + 10, row2Y + 10, { width: cardWidth - 20 });
      doc
        .fillColor(data.summary.netProfit >= 0 ? '#16a34a' : '#dc2626')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(this.formatCurrency(data.summary.netProfit), netProfitX + 10, row2Y + 26, {
          width: cardWidth - 20,
        });

      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 2,
        row2Y,
        cardWidth,
        'GROSS MARGIN',
        `${data.summary.grossProfitMargin.toFixed(1)}%`
      );
      this.drawSummaryCard(
        doc,
        50 + (cardWidth + cardGap) * 3,
        row2Y,
        cardWidth,
        'NET MARGIN',
        `${data.summary.profitMargin.toFixed(1)}%`
      );

      // Row 3: Total Cost of Available Stock
      const row3Y = row2Y + 60;
      this.drawSummaryCard(
        doc,
        50,
        row3Y,
        cardWidth,
        'COST OF AVAILABLE STOCK',
        this.formatCurrency(data.summary.totalCostOfAvailableStock)
      );

      doc.y = row3Y + 65;

      // Monthly Breakdown
      if (data.monthlyBreakdown.length > 0) {
        this.drawSectionTitle(doc, 'Monthly Breakdown');
        const columns = [
          { label: 'Month', x: 55, width: 100 },
          { label: 'Revenue', x: 160, width: 100 },
          { label: 'Expenses', x: 265, width: 100 },
          { label: 'Profit', x: 370, width: 100 },
        ];
        let tableY = this.drawTableHeader(doc, columns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < data.monthlyBreakdown.length; i++) {
          const month = data.monthlyBreakdown[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(month.month, 55, tableY + 6, { width: 100 });
          doc.text(this.formatCurrency(month.revenue), 160, tableY + 6, { width: 100 });
          doc.text(this.formatCurrency(month.expenses), 265, tableY + 6, { width: 100 });
          doc.fillColor(month.profit >= 0 ? '#16a34a' : '#dc2626');
          doc.text(this.formatCurrency(month.profit), 370, tableY + 6, { width: 100 });
          tableY += 20;
        }
      }

      // Expense by Category
      if (data.expenseByCategory.length > 0) {
        doc.y = doc.y + 20;
        this.drawSectionTitle(doc, 'Expense Breakdown by Category');
        const catColumns = [
          { label: 'Category', x: 55, width: 180 },
          { label: 'Amount', x: 240, width: 120 },
          { label: 'Percentage', x: 370, width: 80 },
        ];
        let tableY = this.drawTableHeader(doc, catColumns);

        doc.fillColor(this.textPrimary).fontSize(9).font('Helvetica');
        for (let i = 0; i < Math.min(data.expenseByCategory.length, 10); i++) {
          const cat = data.expenseByCategory[i];
          if (i % 2 === 0) {
            doc.rect(50, tableY, pageWidth, 20).fill('#f9fafb');
          }
          doc.fillColor(this.textPrimary);
          doc.text(
            cat.category.charAt(0).toUpperCase() + cat.category.slice(1).replace('_', ' '),
            55,
            tableY + 6,
            { width: 180 }
          );
          doc.text(this.formatCurrency(cat.amount), 240, tableY + 6, { width: 120 });
          doc.text(`${cat.percentage.toFixed(1)}%`, 370, tableY + 6, { width: 80 });
          tableY += 20;
        }
      }

      this.drawFooter(doc, pageWidth);
      doc.end();
    });
  }
}
